### ISSUE TITLE
Contains does not allow spaces?

### ISSUE THREAD

**Issue by obsidience** [rc0x03/node-libxmljs-dom#5]
Hi,

I'm seeing the following in the Chrome console:

```
> context.find("a:contains('Some')")[0].outerHTML
< "<a target="_blank" href="http://foo.com">Some String with Space</a>"
> context.find("a:contains('Some String with Space')").length
< 0
```

All tests and examples don't appear to show contains using a space.  Was wondering if this is on purpose or a bug. 

Thanks!

**Comment by rchipka** [comment]
If you're using `libxmljs-dom` without Osmosis, you'll need to use the standard `querySelector` and `querySelectorAll` to search the DOM with CSS selectors. Osmosis modifies libxmljs's `find` and `get` functions so that they can use XPath or CSS selectors. However `libxmljs-dom` only intends to be a DOM wrapper so it does not do this. That being said, you can still use XPath and CSS/XPath hybrids with `querySelectorAll`.

If you are using Osmosis then this should work. I've now added tests for `:contains` and `:icontains` that include spaces and all of the tests are passing.

Either way, `:contains` is expected to work exactly like JQuery's [:contains](https://api.jquery.com/contains-selector/).

**Comment by obsidience** [comment]
Got it, thanks!
